apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-credentials
type: Opaque
data:
  db-user: {{ .Values.secret.dbUser | b64enc | quote }}
  db-password: {{ .Values.secret.dbPassword | b64enc | quote }}