name: ENTRA_ID_TESTING

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: arc-org-runner-set
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUB_ID }}

      - name: List RG
        run: az group list